title: DevSecTimes
email: editor@devsectimes.com
description: >- # this means to ignore newlines until "baseurl:"
  Important information for developers - thats it
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-feed

heading_anchors: true

ga_tracking: G-MVYXK9B8DT
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true by default)
